### ISSUE TITLE
"Lost" DB password

### ISSUE THREAD

**Issue by Po-temkin** [Rookiestyle/LockAssist#4] opened 2021-09-14 09:54 UTC
I two times "lost" DB password after using LockAssist.
Everithing work nice, but after reboot the PC i can't unlocked DB using password.
I see "Master key is invalid" message but i didn't change master key.
To LockAssistant i used similar following settings:
Quick Unlock mode - Entry
Expire Time - 30 min
Setting are DB specific - Yes
Soft lock - 1 min

My empty DB in attcachment, password 123456.
Maybe it can help.

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Install plugin
2. Configure
3.  Reboot

OS:  Windows 10
KeePass Version: 2.48/
[PotemkinDB.zip](https://github.com/Rookiestyle/LockAssist/files/7160823/PotemkinDB.zip)
2.49
Plugin Version: 3.0

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment] 2021-09-14 10:10
"Lost" means before the restart the Quick Unlock key works and a free the restart it does not work?

~~~
Quick Unlock lets you unlock a previously opened database without the need to enter the complete password.
~~~

After the restart, is the database loaded and locked?
If yes, LockAssist / Quick Unlock should work
If not, LockAssist / Quick Unlock won't be available and there is no way to change that.

**Comment by Po-temkin** [comment] 2021-09-15 07:49
> "Lost" means before the restart the Quick Unlock key works and after the restart it does not work?
> Are you asked to enter the Quick Unlock key after the restart?
> 
> ```
> Quick Unlock lets you unlock a 
> previously opened database
> without the need to enter the complete password.
> ```
> 
> After the restart, is the database loaded and locked?
> If yes, LockAssist / Quick Unlock should work
> If not, LockAssist / Quick Unlock won't be available and there is no way to change that.

You coudld't  undestand me correctly =)
I don't mean that i can't to unclock DB with QuickUnlock, it's inactive after reboot. I can't do it with full password. I see "Master key is invalid" message but i didn't change master key.

**Comment by Rookiestyle** [comment] 2021-09-15 07:54
> I don't mean that i can't to unclock DB with QuickUnlock, it's inactive after reboot

OK, that's the expected behaviour - after a reboot, the dtaabse is not loaded and therefor Quick Unlock can't work

> I can't do it with full password. I see "Master key is invalid" message but i didn't change master key.

This should not be related to LockAssist although I do have an idea.
When you open the database with the masterkey: Which fields are checked in the key prompt form? Password, Keyfield, User Account)
When you open the database after the reboot: Which fields are checked in the key prompt form? Password, Keyfield, User Account)

Can you please post screenshots when opening the database and when opening after a restart? Screenshots should show the full key prompt window

**Comment by Po-temkin** [comment] 2021-09-15 08:09
> > I don't mean that i can't to unclock DB with QuickUnlock, it's inactive after reboot
> 
> OK, that's the expected behaviour - after a reboot, the dtaabse is not loaded and therefor Quick Unlock can't work
> 
> > I can't do it with full password. I see "Master key is invalid" message but i didn't change master key.
> 
> This should not be related to LockAssist although I do have an idea.
> When you open the database with the masterkey: Which fields are checked in the key prompt form? Password, Keyfield, User Account)
> When you open the database after the reboot: Which fields are checked in the key prompt form? Password, Keyfield, User Account)
> 
> Can you please post screenshots when opening the database and when opening after a restart? Screenshots should show the full key prompt window

Now i disabled QuickUnlock. But i doble checked key promt after i found this trouble. I use only password, no Key File and User Acc.
I think I can make a backup of my DB and try to check this problem another one. I will tell you If i woun't reproduce it again.

**Comment by Rookiestyle** [comment] 2021-09-15 08:45
If you can reproduce it, please post screenshots when opening the database and when opening after a restart? Screenshots should show the full key prompt window

**Comment by Po-temkin** [comment] 2021-09-16 13:33
> If you can reproduce it, please post screenshots when opening the database and when opening after a restart? Screenshots should show the full key prompt window

![Screenshot_2](https://user-images.githubusercontent.com/66019363/133621550-d405a0dc-9702-4bd6-bba8-f054a54f9604.png)

**Comment by Rookiestyle** [comment] 2021-09-16 14:52
So you're saying that you restart your PC and after restart KeePass is still active and both databases are loaded and locked?

In the screenshot, if you enter your masterkey it should work. If not, the masterkey is incorrect and this is not related to LockAssist.

In the screenshot, if you enter the Quick Unlock key it will not work.


I was not able to reproduce this.
Do you do a restart or "save energy" or something else?

**Comment by Rookiestyle** [comment] 2021-09-16 15:33
I finally can reproduce it using these steps:

1. Configure LockAssist
2. Lock database
3. Enter power save mode (**Not restart**)

**Comment by Rookiestyle** [comment] 2021-09-16 19:31
The fix for the isse I described above is almost done.

To verify whether it will work for you as well, please do the following
1. Open DB (Quick Unlock mode should still be: Entry)
2. Lock DB 
3. Quick Unlock
4. Lock DB
5. Quick Unlock

Step 3 should work, step 5 should fail, right?

**Comment by Po-temkin** [comment] 2021-09-17 20:57
> The fix for the isse I described above is almost done.
> 
> To verify whether it will work for you as well, please do the following
> 
> 1. Open DB (Quick Unlock mode should still be: Entry)
> 2. Lock DB
> 3. Quick Unlock
> 4. Lock DB
> 5. Quick Unlock
> 
> Step 3 should work, step 5 should fail, right?

I apologize for not answering for a long time. I wiil check this steps tomorrow.
About my loaded base - sorry, i just cleaned my own and changed password. I forgot create QuikUnlock entry.
I have promlem not with QuickUnlock. But if i seted up QuickUnlock i can "corrupt" my DB over time and can't unlock it with master key.

**Comment by Rookiestyle** [comment] 2021-09-18 08:23
If you experience this issue with the new release, please post it hre.
I will reopen this issue then

**Closed** 2021-09-18 08:22 UTC
Labels: bug, more information required

**Comment by atsdai** [comment] 2025-08-30 23:00
Hello. I have encountered a problem where the database becomes corrupted when unlocking without the key file available and with automatic saving enabled. Here is an example:

1. I create a new database and assign it a master key composed of the password ‘test’ and a key file in v2.0 format.
2. I activate LockAssist with Quick Unlock in either of the two modes (‘Database password’ or ‘Quick Unlock entry only’).
3. I lock the database.
4. I change the name or location of the key file.
5. I try to unlock the database by providing the previously configured unlock password, and then an exception pops up. If I click Continue instead of Exit, the database is unlocked, but if I make a change (since automatic saving is enabled), the compound master key is corrupted and there is no way to reopen it.

It occurs to me that in cases where the key file is accessed remotely or is on a portable device, or you simply change its name or location while the database is locked and you have auto-save enabled when you make changes or when you close the database, it is possible that if you are not paying attention when the error occurs and you click Continue using the application, the database will be irreparably corrupted.

Thank you for your work and dedication.

Translated with [DeepL.com]

Keepass version 2.59 (x64)
LockAssist version 3.6

<img width="441" height="165" alt="Image" src="https://github.com/user-attachments/assets/15410c9d-8993-493d-aea7-923e64b23779" />

[exception.txt](https://github.com/user-attachments/files/22061561/exception.txt)

**Comment by atsdai** [comment] 2025-08-31 20:15
Hi. 
The problem is that once the exception appears, if you click Continue, it may seem like there is no problem, but if you modify a record and save it (manually or automatically), the composite master key becomes corrupted and it is no longer possible to open the database again, either with the renamed key file or with its original name.
Thank you.

Translated with [DeepL.com]

**Comment by Rookiestyle** [comment] 2025-09-02 04:17
> Now the exception no longer occurs when the key file cannot be found during unlocking, and the combined master key is no longer corrupted when saving. I can unlock (without the key file), make changes to the database, save, close, and reopen it with the key file (even with the name changed) without any problems.

Thanks for testing it

> The number of failed attempts to unlock the database has changed. It is now 3 attempts instead of 1. Could you add a box to configure it? Although 1, as before, was fine.

This is something I'm working on currently.
In the beta version that I attached in my previous post the default is 3 because you also have 3 attempts to open the database with the master key.
I think I will change it to 1 as default and allow up to 3 atempts in the plugin's options.

> With the modification you have made now, is it still secure? In other words, is the combined master key still protected in memory against a dump?

Yes

**Comment by atsdai** [comment] 2025-10-05 23:53
Hello.

The database has been corrupted again. I had several databases open and global locking/unlocking configured. I don't know if I missed an unlock in the sequence. To be honest, I didn't note down the exact combination that caused it to happen. What I can say is that, like last time, the key files were not accessible.  
If I can, I'll look into it this week and post the sequence log so it can be replicated.

Thank you. Best regards.

Translated with DeepL.com (free version)

**Comment by atsdai** [comment] 2025-10-06 12:39
I will list what I have tried so far that causes problems.

NOTE: Remove the key files from the Keepass scope once the databases are open. And disable the option to keep the master key in memory.

When locking globally and unlocking again, if an unlock fails in the sequence, the next one or ones, even if the unlock key is entered correctly, will display a message stating that the master key is incorrect. However, in this case, the database will not yet be corrupted.

Changing the number of attempts and the subsequent question of whether you want to make the changes global (clicking ‘NO’ to make them global) with the other databases locked and clicking save all causes a message to appear stating that the composite master key is invalid and ends up with a corrupted database. The curious thing is that I think it only happens in a database that is between two databases (or at least not at the ends, I would have to do more testing).

I hope it makes sense once it has been run through the online translator.


[Debug_LockAssist_20251006T114624Z.zip](https://github.com/user-attachments/files/22721902/Debug_LockAssist_20251006T114624Z.zip)

I am also including the files used to facilitate testing. The database password is ‘test’ and the unlock password is ‘tt’.

[KP_LOCKASSIST_TEST.zip](https://github.com/user-attachments/files/22722329/KP_LOCKASSIST_TEST.zip)

**Comment by atsdai** [comment] 2025-11-04 22:44
This also happens with version 2.60.

The process is as follows:
1. Open the database with the master key.
2. Lock it.
3. Close it from File->Close (without closing Keepass and with the database still locked).
4. When you reopen it, entering the password and the key file, it no longer accepts the compound master key.
5. Until Keepass is completely closed, it does not allow you to reopen it.

I hope I have explained myself clearly.

Translated with DeepL.com (free version)
